### ISSUE TITLE
[Web] Campos "Vegetação" e "Relevo" são exigidos mesmo com valor já selecionado

### ISSUE THREAD

**Issue by edvaldoszy** [utfpr/hcf-painel#41]
Ao editar um tombo já existe, após preencher os campos obrigatórios (mencionado aqui) o sistema retorna erro dizendo que "Relevo" e "Vegetação" contém valor inválido mesmo estando preenchidos na tela.

Tombo de teste: https://hcf.cm.utfpr.edu.br/tombos/37531

![Image](https://github.com/utfpr/hcf-painel/assets/3211168/f3074648-0791-45b1-bad8-2959015f782f)

## Acceptance Criteria

| # | Given | When | Then |
| -- | -- | -- | -- |
| 1 | O usuário está editando um tombo existente e os campos "Vegetaçãoe" e "Relevos" já estão preenchidos | O usuário tenta salvar os tombo | O dados do tombo devem ser salvos com sucesso |

**Comment by William-Reticena** [comment]
# Testes
Fiz o teste a partir da branch development e obtive os mesmo erros mostrados no seu gif. Porém fazendo o mesmo procedimento na branch relacionada com a issue #44, percebi que isso não acontece mais. Porém percebi um erro quando eu crio e depois eu edito um tombo.

# Problema na hora de pegar os dados do tombo para a edição (GET)
Quando eu crio um tombo, os campos de relevo, vegetação, etc. são enviados como um id, porém na hora que eu requisito os dados para a edição, ao invés dele me retornar o id do relevo, vegetação, etc. Ele me retorna a string equivalente ao id, o back precisa ajustar o retorno desses campos para me retornar o id ao invés do valor ligado a ele.

![Image](https://github.com/utfpr/hcf-painel/assets/66524335/f52131e4-0f0e-42be-9904-ef450ff288c0)

# Demonstração da branch relacionada a issue #44 

https://github.com/utfpr/hcf-painel/assets/66524335/1f5b8692-9f7e-445e-839f-25b1275b93bb

![Image](https://github.com/utfpr/hcf-painel/assets/66524335/33967fe2-18ed-42b7-9461-7c9c677252ee)

![Image](https://github.com/utfpr/hcf-painel/assets/66524335/93c31aa0-a108-4532-bdb7-fcfcc9697dc3)
